# Generated by Django 3.1.2 on 2020-11-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_night', '0003_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movieType',
            field=models.TextField(null=True),
        ),
    ]
