# Generated by Django 3.1.2 on 2020-11-17 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_night', '0004_review_movietype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
