# Generated by Django 3.1.2 on 2020-11-19 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_night', '0005_delete_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='INTEGER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MID', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='WatchList',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ALLIDS', to='movie_night.integer'),
        ),
    ]
