# Generated by Django 3.1.2 on 2020-11-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_night', '0007_auto_20201120_0021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='INTEGER',
        ),
    ]
