# Generated by Django 3.1.2 on 2020-11-20 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_night', '0010_watchlistlink_t'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='review',
            name='timestamp',
        ),
    ]
